(* 

To run the program :
1. ml-lex mdtab.lex 
2. CM.make("sources.cm")
2. use "test.sml"
3. markdown "fileName"
*)

(* Tokens now automatically generated by yacc *)
(* use "tokens.sml"; *)

(* Parser *)
(* use "mdtab.grm.sig"; *)
(* use "mdtab.grm.sml"; *)

(* Lexer *)
(* use "mdtab.lex.sml"; *)

(* Main *)
(* use "main.sml"; *)

(* parse_file function accessible through markdown variable *)
val markdown = Main.parse_file;

(* Display usage instructions *)
Main.main();